In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvdG9tL0RvY3VtZW50cy9jb2RlL3NpbS10b29scy9kb2NzLzAyX292cw=='
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
# globals()["__spec__"] = None

{"/home/tom/miniforge3/envs/sim_tools/lib/python3.11/importlib/_bootstrap.py": 1744325552.7634213, "/home/tom/miniforge3/envs/sim_tools/lib/python3.11/importlib/_bootstrap_external.py": 1744325552.7604213, "/home/tom/miniforge3/envs/sim_tools/lib/python3.11/zipimport.py": 1744325551.5044155, "/home/tom/miniforge3/envs/sim_tools/lib/python3.11/codecs.py": 1744325551.0734136, "/home/tom/miniforge3/envs/sim_tools/lib/python3.11/encodings/aliases.py": 1744325552.0134177, "/home/tom/miniforge3/envs/sim_tools/lib/python3.11/encodings/__init__.py": 1744325552.1864185, "/home/tom/miniforge3/envs/sim_tools/lib/python3.11/encodings/utf_8.py": 1744325552.3664193, "/home/tom/miniforge3/envs/sim_tools/lib/python3.11/abc.py": 1744325551.0164132, "/home/tom/miniforge3/envs/sim_tools/lib/python3.11/io.py": 1744325551.2044141, "/home/tom/miniforge3/envs/sim_tools/lib/python3.11/stat.py": 1744325551.394415, "/home/tom/miniforge3/envs/sim_tools/lib/python3.11/_collections_abc.py": 1744325551.0814135, "/h

In [2]:
# pylint: disable=missing-module-docstring,invalid-name

# run this first to install the OvS procedures so we can use them in the
# tutorial.
# !pip install sim-tools

In [3]:
import numpy as np

In [4]:
from sim_tools.ovs.evaluation import Experiment
from sim_tools.ovs.fixed_budget import OCBA, OCBAM
from sim_tools.ovs.indifference_zone import KN, KNPlusPlus
from sim_tools.ovs.toy_models import (custom_gaussian_model,
                                      gaussian_sequence_model,
                                      random_gaussian_model,
                                      ManualOptimiser)

In [5]:
manual_opt = ManualOptimiser(model=gaussian_sequence_model(1, 10),
                             n_designs=10)

In [6]:
print(manual_opt)

ManualOptimiser(model=BanditCasino(), n_designs=10, verbose=False)


In [7]:
manual_opt.simulate_designs(replications=3)

In [8]:
print(manual_opt.allocations)

[3 3 3 3 3 3 3 3 3 3]


In [9]:
np.set_printoptions(precision=1) # this is a hack to view at 1 decimal place.
print(manual_opt.means)

[1.9 1.7 2.8 4.3 4.8 5.4 6.7 8.6 8.8 9.1]


In [10]:
print(manual_opt.vars)

[3.3 0.3 0.5 1.3 0.6 0.1 2.3 0.1 0.1 0. ]


In [11]:
manual_opt.simulate_designs(design_indexes=[7, 8, 9], replications=1)

In [12]:
print(manual_opt.allocations)

[3 3 3 3 3 3 3 4 4 4]


In [13]:
print(manual_opt.means)

[1.9 1.7 2.8 4.3 4.8 5.4 6.7 8.7 8.8 9.1]


In [14]:
print(manual_opt.vars)

[3.3 0.3 0.5 1.3 0.6 0.1 2.3 0.2 0.1 0. ]


In [15]:
#create random problem
rnd_model = random_gaussian_model(mean_low=5, mean_high=25,
                                  var_low=0.5, var_high=2.5,
                                  n_designs=10)

#create manual optimiser for you to use.
manual_opt = ManualOptimiser(model=rnd_model, n_designs=10)

In [16]:
#insert your code here...


In [17]:
N_DESIGNS = 10
DELTA = 1.0
ALPHA = 0.05
N_0 = 5

#first we create the simulation model.
model = gaussian_sequence_model(1, N_DESIGNS)

#then we create the KN R&S object and pass in our parameters.
#note that this doesn't run the optimisation yet.
kn = KN(model=model,
        n_designs=N_DESIGNS,
        delta=DELTA,
        alpha=ALPHA,
        n_0=N_0)

In [18]:
#quickly check if KN is parameterised as expected
print(kn)

KN(n_designs=10, delta=1.0, alpha=0.05, n_0=5, obj=max)


In [19]:
#this runs KN (you can run this cell multiple times if you wish)
best_design = kn.solve()

#print out the results
print(f'best design\t{best_design}')
print(f'allocations\t{kn._allocations}')
print(f'total reps\t{kn._allocations.sum()}')

best design	[9]
allocations	[ 5  5  5  5  5  5  6  5 10 11]
total reps	62


In [20]:
knpp = KNPlusPlus(model=model,
                  n_designs=N_DESIGNS,
                  delta=DELTA,
                  alpha=ALPHA,
                  n_0=N_0)

best_design = knpp.solve()
print(f'best design\t{best_design}')
print(f'allocations\t{knpp._allocations}')
print(f'total reps\t{knpp._allocations.sum()}')

best design	[9]
allocations	[ 5  6  5  5  7  7  7  9 12 13]
total reps	76


In [21]:
#the code to set up the simulation model has been provided below.
N_DESIGNS = 100
DELTA = 1.0
ALPHA = 0.05
N_0 = 5

#first we create the simulation model.
model = gaussian_sequence_model(1, N_DESIGNS)

In [22]:
# Your code goes here...

# Hint 1. you need to create KN and KNPlusPlus objects, pass in the simulation
# model and run them.

# Hint 2. try running the models a few times.



In [23]:
# set problem parameters and create simulation model.

N_DESIGNS = 10
N_0 = 20
DELTA = 0.15
ALPHA = 0.05

#change the value of seed.
SEED = 999

means = [4, 4.1, 4.2, 4, 4.1, 4.3, 4, 4.1, 4.2, 4.2]
variances = [1, 1, 1, 0.1, 0.1, 10, 10, 10, 10, 0.1]

guass_model = custom_gaussian_model(means, variances)

#print out which design indexes are in the indifference zone
print(np.where(4.3 - np.array(means) <= DELTA)[0])

[2 5 8 9]


In [24]:
# create an instance of KN and solve.

kn = KN(model=guass_model,
        n_designs=N_DESIGNS,
        delta=DELTA,
        alpha=ALPHA,
        n_0=N_0)

np.random.seed(SEED)
best_design = kn.solve()

#print out the results
print(f'best design\t{best_design}')
print(f'allocations\t{kn._allocations}')
print(f'total reps\t{kn._allocations.sum()}')

best design	[2]
allocations	[  415   314 41678    20    20    29  6697 41677 23238    20]
total reps	114108


In [25]:
# use KN++ on the same problem
knpp = KNPlusPlus(model=guass_model,
                  n_designs=N_DESIGNS,
                  delta=DELTA,
                  alpha=ALPHA,
                  n_0=N_0)

# we use the same random seed to help with comparison.
np.random.seed(SEED)
best_design = knpp.solve()

# print out the results
print(f'best design\t{best_design}')
print(f'allocations\t{knpp._allocations}')
print(f'total reps\t{knpp._allocations.sum()}')

best design	[5]
allocations	[  190   200   107    20    20 28167  8476  7204 28166 15383]
total reps	87933


In [26]:
N_DESIGNS = 10

#remember that delta is not the same as in IZ!
#it is the amount of replication to allocate at each stage.
DELTA = 5

#the initial stage will run 5 reps of each design.
N_0 = 5

BUDGET = 1000

#first we create the simulation model.
model = gaussian_sequence_model(1, N_DESIGNS)

ocba = OCBA(model=model,
            n_designs=N_DESIGNS,
            budget=BUDGET,
            delta=DELTA,
            n_0=N_0,
            obj='max')

In [27]:
print(ocba)

OCBA(n_designs=10, budget=1000, delta=5, n_0=5, obj=max)


In [28]:
best_design = ocba.solve()

#print out the results
print(f'best design\t{best_design}')
print(f'allocations\t{ocba._allocations}')
print(f'total reps\t{ocba._allocations.sum()}')

best design	9
allocations	[  5  11   5   5  15   5   5 101 426 422]
total reps	1000


In [30]:
#this is the budget you can vary.
BUDGET = 75

#you could also vary delta.  What happens if delta = 1?
DELTA = 5

N_DESIGNS = 10
N_0 = 5

ocba = OCBA(model=model,
            n_designs=N_DESIGNS,
            budget=BUDGET,
            delta=DELTA,
            n_0=N_0,
            obj='max')

#create an experiment and repeat 1000 times.
exp = Experiment(env=model, procedure=ocba, best_index=9, objective='max',
                 replications=1000)

results = exp.execute()

#print the probability of correct selection achieved.
print(f'PCS={results.p_correct_selections}')

PCS=0.999


In [31]:
# KN++ needed a large budget to reach its desired precision.
# We will try a smaller budgets here
BUDGET = 20000
DELTA = 5
N_DESIGNS = 10
N_0 = 5

means = [4, 4.1, 4.2, 4, 4.1, 4.3, 4, 4.1, 4.2, 4.2]
variances = [1, 1, 1, 0.1, 0.1, 10, 10, 10, 10, 0.1]

guass_model = custom_gaussian_model(means, variances)

ocba = OCBA(model=guass_model,
            n_designs=N_DESIGNS,
            budget=BUDGET,
            delta=5,
            n_0=50,
            obj='max')

# create an experiment and repeat 10 times (in practice we would use more!)
exp = Experiment(env=guass_model, procedure=ocba, best_index=5,
                 objective='max', replications=10)

results = exp.execute()

# the probability of correct selection achieved.
print(f'PCS={results.p_correct_selections}')

# IF YOU REMEMBER FROM Example 2 THE DESIGNS IN THE IZ WERE [2 5 8 9]
# Let's print out the selections made...
print(f'selected designs: {results.selections}')

# the average of the best_mean - selected_design_mean for each rep of the exp.
print(f'EOC={results.expected_opportunity_cost}')

PCS=0.7
selected designs: [5 5 5 8 5 5 5 9 2 5]
EOC=0.029999999999999895


In [32]:
N_DESIGNS = 10
BUDGET = 1000
DELTA = 5
N_0 = 5

#you can vary this parameter to change the number selected.
M = 3

guass_model = gaussian_sequence_model(1, N_DESIGNS)

ocbam = OCBAM(model=guass_model,
              n_designs=N_DESIGNS,
              budget=BUDGET,
              delta=DELTA,
              n_0=N_0,
              m=M,
              obj='max')

In [33]:
print(ocbam)

OCBA(n_designs=10, m=3, budget=1000, delta=5, n_0=5, obj=max)


In [34]:
#print out the results
best_designs = ocbam.solve()
print(f'best designs\t{best_designs}')
print(f'allocations\t{ocbam._allocations}')
print(f'total reps\t{ocbam._allocations.sum()}')

best designs	[7 8 9]
allocations	[ 20  23  21  38  39  75  79 303 302 100]
total reps	1000


In [35]:
N_DESIGNS = 100
BUDGET = 1000
DELTA = 1
N_0 = 5

#you can vary this parameter to change the number selected.
M = 3

guass_model = gaussian_sequence_model(1, N_DESIGNS)


#insert your code here
#ocbam = ?

In [36]:
#print out the results
best_designs = ocbam.solve()
print(f'best designs\t{best_designs}')
print(f'allocations\t{ocbam._allocations}')
print(f'total reps\t{ocbam._allocations.sum()}')

best designs	[7 8 9]
allocations	[ 20  23  21  38  39  75  79 303 302 100]
total reps	1000
